name: Deploy Next.js to VPS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v5.0.0
            
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'  # Adjust Node.js version as needed

      - name: Create env file
        run: |
          touch .env
          echo WC_CONSUMER_KEY=ck_7aa75663b748232d7216f0d2bb63cb15dddc5b50 >> .env
          echo WC_CONSUMER_SECRET=cs_c5b50698e88217fc8578f60ddabc90fb72177227 >> .env
          echo EMAIL_USER=info@hrfleek.com >> .env
          echo EMAIL_PASS=Sat17556 >> .env
          cat .env

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test  # Ensure you have tests configured

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: .next

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS using SSH with Password
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "
            cd /var/www/html/hrfleek-v2 || git clone https://github.com/barizicommunications/hrfleek-v2.git /var/www/html/hrfleek-v2;
            cd /var/www/html/hrfleek-v2;
            git pull origin master;
            npm install;
            npm run build;
            pm2 restart hrfleek || pm2 start npm --name 'hrfleek' -- start;
          "
